export const songs = [
  {
    artist: 'Hum',
    artwork: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Hum_-_You%27d_Prefer_an_Astronaut.png',
    // artwork: 'https://picsum.photos/300?random=10',
    id: '1',
    album: "You'd Prefer an Astronaut",
    title: 'Stars',
    url: 'file:///storage/emulated/0/Music/Stars.mp3'
  },
  {
    title: 'Auntie Diaries',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=10',
    url: require('../../assets/songs/06_Auntie_Diaries.m4a'),
    id: '2',
  },

  {
    title: 'Crown',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=11',
    // url: require('../../assets/songs/02_Crown.m4a'),
    id: '3',
  },
  {
    title: 'Count Me Out',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=9',
    // url: require('../../assets/songs/01_Count_Me_Out.m4a'),
    id: '4',
  },
  {
    title: 'Auntie Diaries',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=10',
    url: require('../../assets/songs/06_Auntie_Diaries.m4a'),
    id: '5',
  },
  {
    artist: 'Hum',
    artwork: 'https://picsum.photos/300?random=1',
    id: '6',
    album: "You'd Prefer an Astronaut",
    title: 'Stars',
    // url: 'file:///storage/emulated/0/Music/Stars.mp3'
  },
  {
    title: 'Crown',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=11',
    // url: require('../../assets/songs/02_Crown.m4a'),
    id: '7',
  },
  {
    title: 'Count Me Out',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=9',
    // url: require('../../assets/songs/01_Count_Me_Out.m4a'),
    id: '8',
  },
  {
    title: 'Auntie Diaries',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=10',
    url: require('../../assets/songs/06_Auntie_Diaries.m4a'),
    id: '9',
  },
  {
    artist: 'Hum',
    artwork: 'https://picsum.photos/300?random=1',
    id: '10',
    album: "You'd Prefer an Astronaut",
    title: 'Stars',
    // url: 'file:///storage/emulated/0/Music/Stars.mp3'
  },
  {
    title: 'Crown',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=11',
    // url: require('../../assets/songs/02_Crown.m4a'),
    id: '11',
  },
  {
    title: 'Count Me Out',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=9',
    // url: require('../../assets/songs/01_Count_Me_Out.m4a'),
    id: '12',
  },
  {
    title: 'Auntie Diaries',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=10',
    url: require('../../assets/songs/06_Auntie_Diaries.m4a'),
    id: '13',
  },
  {
    artist: 'Hum',
    artwork: 'https://picsum.photos/300?random=1',
    id: '14',
    album: "You'd Prefer an Astronaut",
    title: 'Stars',
    // url: 'file:///storage/emulated/0/Music/Stars.mp3'
  },
  {
    title: 'Crown',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=11',
    // url: require('../../assets/songs/02_Crown.m4a'),
    id: '15',
  },
  {
    title: 'Count Me Out',
    artist: 'Kendrick Lamar',
    album: 'Mr. Morale & the Big Steppers',
    artwork: 'https://picsum.photos/300?random=9',
    // url: require('../../assets/songs/01_Count_Me_Out.m4a'),
    id: '16',
  },

]